/** Synthetic problems for deterministic logic tests (not machine artifacts). */

export function makeProblem(overrides = {}) {
  return {
    problem_id: "problem_0001",
    canonical_signature: "X|table|x",
    problem_type: "GRAIN_PROBLEM",
    classification: "confirmed_conflict",
    priority: "P0",
    severity: "critical",
    status: "candidate",
    human_validated: false,
    human_review_required: false,
    scope: "table",
    scope_key: "dme_ads.table_a",
    table_keys: ["dme_ads.table_a"],
    process_keys: ["process_candidate_001"],
    grain_keys: ["grain_candidate_001"],
    object_keys: [],
    finding_ids: ["model_finding_0001"],
    finding_count: 1,
    finding_types: ["grain_conflict"],
    affected_table_count: 1,
    signals: [],
    evidence_strength: "strong",
    evidence_total: 9,
    evidence_truncated: false,
    evidence_type_counts: { GRAIN: 3, TABLE: 1 },
    impact_types: ["GRAIN_INCONSISTENCY"],
    root_cause: "MULTIPLE_GRAINS_IN_ONE_MODEL",
    description: "desc",
    impact: "impact",
    unresolved_reason: "unresolved",
    human_question: "question",
    rationale: {},
    evidence: [],
    evidence_sample_limit: 5,
    ...overrides,
  };
}

export function fixtureProblems() {
  return [
    makeProblem({
      problem_id: "problem_0010",
      priority: "P1",
      problem_type: "MODEL_DUPLICATION",
      classification: "technical_copy_candidate",
      evidence_strength: "moderate",
      affected_table_count: 24,
      scope_key: "dme_cdm.dup_target",
      table_keys: ["dme_cdm.dup_target", "dme_ods.dup_source"],
      process_keys: ["process_candidate_013"],
      status: "candidate",
    }),
    makeProblem({
      problem_id: "problem_0002",
      priority: "P0",
      problem_type: "GRAIN_PROBLEM",
      evidence_strength: "strong",
      affected_table_count: 3,
      scope_key: "dme_ads.grain_table",
      table_keys: ["dme_ads.grain_table"],
      process_keys: ["process_candidate_004"],
      status: "review_required",
    }),
    makeProblem({
      problem_id: "problem_0007",
      priority: "P2",
      problem_type: "UNKNOWN_MODEL",
      classification: "NO_EVIDENCE",
      evidence_strength: "weak",
      affected_table_count: 1,
      scope_key: "dme_dwd.unknown_table",
      table_keys: ["dme_dwd.unknown_table"],
      process_keys: [],
      status: "candidate",
    }),
    makeProblem({
      problem_id: "problem_0005",
      priority: "P0",
      problem_type: "MIXED_RESPONSIBILITY",
      evidence_strength: "strong",
      affected_table_count: 2,
      scope_key: "dme_ads.mixed_table",
      table_keys: ["dme_ads.mixed_table"],
      process_keys: ["process_candidate_005"],
      status: "candidate",
    }),
    makeProblem({
      problem_id: "problem_0100",
      priority: "P3",
      problem_type: "PROCESS_MODEL_ALIGNMENT",
      evidence_strength: "weak",
      affected_table_count: 0,
      scope: "process",
      scope_key: "process_candidate_013",
      table_keys: [],
      process_keys: ["process_candidate_013"],
      status: "candidate",
    }),
  ];
}
