"""兼容层：Analysis Scope Rules 已迁移到 ``analysis/scope/`` 包。

本模块不再实现任何规则，只把新包的公开接口重新导出到旧路径，
保证既有 ``from ..inventory.scope import ...`` 仍然可用，
且实际调用全部落到唯一实现 ``data_platform_analysis.analysis.scope``。

新代码请直接导入 ``data_platform_analysis.analysis.scope``。
"""

from __future__ import annotations

from ..scope import (
    CLASSIFICATIONS,
    CONDITION_KINDS,
    CONTENT_GAP_STATES,
    CONTENT_READ_LIMIT,
    CONTENT_STATE_EMPTY_TEXT,
    CONTENT_STATE_NOT_CHECKED,
    CONTENT_STATE_NOT_COLLECTED,
    CONTENT_STATE_PATH_MISSING,
    CONTENT_STATE_PRESENT,
    CONTENT_STATE_READ_ERROR,
    CONTENT_STATES,
    EXCLUSION_IDENTITY,
    EXCLUSION_INFORMAL,
    EXPECTATION_NOT_REQUIRED,
    EXPECTATION_REQUIRED,
    EXPECTATION_UNKNOWN,
    EXPECTATIONS,
    INFORMAL_NUMERIC_SUFFIX,
    INFORMAL_SEPARATOR,
    RULE_TYPE_CONTENT_STATE,
    RULE_TYPE_INFORMAL_TASK,
    RULE_TYPE_NODE_IDENTITY,
    RULE_TYPE_SQL_ELIGIBILITY,
    RULE_TYPES,
    SQL_BLOCKER_CONTENT,
    SQL_BLOCKER_IDENTITY,
    SQL_BLOCKER_INFORMAL,
    SQL_BLOCKER_NODE_TYPE,
    SQL_BLOCKERS,
    ContentCheckConfig,
    FileScope,
    FileScopeDecision,
    FileScopeStats,
    ScopeCondition,
    ScopeResult,
    ScopeRule,
    ScopeRules,
    ScopeRulesError,
    build_file_scope,
    classify_file,
    content_expectation,
    content_state_of,
    excluded_tasks_payload,
    load_scope_rules,
    match_informal_name,
    review_tasks_payload,
    sql_candidates_payload,
)

__all__ = [
    "CLASSIFICATIONS",
    "CONDITION_KINDS",
    "CONTENT_GAP_STATES",
    "CONTENT_READ_LIMIT",
    "CONTENT_STATE_EMPTY_TEXT",
    "CONTENT_STATE_NOT_CHECKED",
    "CONTENT_STATE_NOT_COLLECTED",
    "CONTENT_STATE_PATH_MISSING",
    "CONTENT_STATE_PRESENT",
    "CONTENT_STATE_READ_ERROR",
    "CONTENT_STATES",
    "ContentCheckConfig",
    "EXCLUSION_IDENTITY",
    "EXCLUSION_INFORMAL",
    "EXPECTATIONS",
    "EXPECTATION_NOT_REQUIRED",
    "EXPECTATION_REQUIRED",
    "EXPECTATION_UNKNOWN",
    "INFORMAL_NUMERIC_SUFFIX",
    "INFORMAL_SEPARATOR",
    "RULE_TYPES",
    "RULE_TYPE_CONTENT_STATE",
    "RULE_TYPE_INFORMAL_TASK",
    "RULE_TYPE_NODE_IDENTITY",
    "RULE_TYPE_SQL_ELIGIBILITY",
    "SQL_BLOCKERS",
    "SQL_BLOCKER_CONTENT",
    "SQL_BLOCKER_IDENTITY",
    "SQL_BLOCKER_INFORMAL",
    "SQL_BLOCKER_NODE_TYPE",
    "FileScope",
    "FileScopeDecision",
    "FileScopeStats",
    "ScopeCondition",
    "ScopeResult",
    "ScopeRule",
    "ScopeRules",
    "ScopeRulesError",
    "build_file_scope",
    "classify_file",
    "content_expectation",
    "content_state_of",
    "excluded_tasks_payload",
    "load_scope_rules",
    "match_informal_name",
    "review_tasks_payload",
    "sql_candidates_payload",
]
